map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 80;
    server_name scinside.local localhost _;

    resolver 127.0.0.11 valid=30s ipv6=off;

    set $frontend_upstream vkr-frontend:5173;
    set $backend_upstream vkr-backend:9000;

    location = /api {
        include /etc/nginx/symfony;
    }

    location ^~ /api/ {
        include /etc/nginx/symfony;
    }

    location / {
        proxy_pass http://$frontend_upstream;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
